name: Release

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-upload:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir mydir
          echo hi > mydir/a.txt
          ls -al mydir

      - name: Generate release tag
        id: tag
        run: |
          set -euxo pipefail
          TAG=Build_$(date +"%Y.%m.%d_%H-%M-%S")
          echo "release_tag=$TAG" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: name1
          path: mydir
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: mydir

      - uses: actions/upload-artifact@v3
        with:
          name: name2
          path: mydir/a.txt
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          path: mydir/a.txt
