name: Release

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-upload:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest

    steps:
      # ref: https://github.com/dart-lang/sdk/wiki/Building

      - name: Generate release tag
        id: tag
        run: |
          set -euxo pipefail
          TAG=Build_$(date +"%Y.%m.%d_%H-%M-%S")
          echo "release_tag=$TAG" >> $GITHUB_OUTPUT

      - run: |
          set -euxo pipefail

          sudo apt-get install git python3 curl xz-utils
          
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:$PWD/depot_tools"

          mkdir dart-sdk
          cd dart-sdk
          fetch dart
          ls -al
          
          cd sdk
          export ASAN_OPTIONS="handle_segv=0:detect_leaks=1:detect_stack_use_after_return=0:disable_coredump=0:abort_on_error=1"
          export ASAN_SYMBOLIZER_PATH="$PWD/buildtools/linux-x64/clang/bin/llvm-symbolizer"
          ./tools/build.py --no-goma --mode release --arch x64 --sanitizer asan runtime runtime_precompiled create_sdk
          ls -al

      - run: |
          ls -al dart-sdk
          ls -al dart-sdk/sdk
          ls -al dart-sdk/sdk/out
          ls -al dart-sdk/sdk/out/ReleaseASANX64
          ls -al dart-sdk/sdk/out/ReleaseASANX64/dart-sdk
          ls -al dart-sdk/sdk/out/ReleaseASANX64/dart-sdk/bin
          dart-sdk/sdk/out/ReleaseASANX64/dart-sdk/bin/dart --version

      - uses: actions/upload-artifact@v3
        with:
          name: Dart_Out_ReleaseASANX64_DartBinary
          path: dart-sdk/sdk/out/ReleaseASANX64/dart-sdk/bin/dart
      - uses: actions/upload-artifact@v3
        with:
          name: Dart_Out_ReleaseASANX64
          path: dart-sdk/sdk/out/ReleaseASANX64/

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: dart-sdk/sdk/out/ReleaseASANX64/dart-sdk/bin/dart

      # for debug
#      - if: ${{ failure() }}
#        uses: mxschmitt/action-tmate@v3
#        with:
#          detached: true
#      - if: ${{ failure() }}
#        name: Sleep forever
#        run: sleep 1000000
#
