name: Release

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-upload:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir mydir
          echo hi > mydir/a.txt
          ls -al mydir

      - uses: actions/upload-artifact@v3
        with:
          name: name1
          path: mydir
      - uses: softprops/action-gh-release@v1
        with:
          name: ReleaseExperimentHello
          files: mydir

      - uses: actions/upload-artifact@v3
        with:
          name: name2
          path: mydir/a.txt
      - uses: softprops/action-gh-release@v1
        with:
          name: ReleaseExperimentHello
          path: mydir/a.txt
