name: Release

on:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-upload:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir d1
          echo hi > d1/a.txt
          mkdir d2
          echo ha > d2/b.txt
          ls -al d1
          ls -al d2

      - uses: actions/upload-artifact@v3
        with:
          name: name1
          path: d1
      - uses: softprops/action-gh-release@v1
        with:
          name: ReleaseExperimentHello
          files: d1

      - uses: actions/upload-artifact@v3
        with:
          name: name2
          path: d2
      - uses: softprops/action-gh-release@v1
        with:
          name: ReleaseExperimentHello
          files: d2
